name: Validate

on:
  push:
    branches-ignore:
      - main  # handled separately
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install git+https://github.com/ayaka14732/python-jyutping.git@167865b
      - name: Validate
        run: python scripts/validate.py
